# https://github.com/lycheeverse/lychee

name: Check for any broken URLs

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check links in repository
        uses: lycheeverse/lychee-action@v2.4.0
        with:
          fail: false
          failIfEmpty: false

